// Generated by CoffeeScript 1.7.1
(function() {
  var DatabaseProvider, User, config, databaseProvider, hasRequiredParameters, restify, server, util;

  restify = require('restify');

  config = require('./config');

  DatabaseProvider = require('./lib/database_provider');

  databaseProvider = new DatabaseProvider(config.database);

  User = require('./user');

  util = require('./util');

  hasRequiredParameters = util.hasRequiredParameters;

  server = restify.createServer({
    name: 'LunchAPI',
    version: "0.0.1"
  });

  server.use(restify.bodyParser());

  server.post('/register', function(req, res, next) {
    var password, username;
    if (!hasRequiredParameters(req.params, 'username', 'password')) {
      return next(new restify.MissingParameterError("username and password is required."));
    }
    username = req.params.username;
    password = req.params.password;
    return User.register(username, password, databaseProvider).then(function() {
      return res.send("OK");
    })["catch"](function(err) {
      console.log(err);
      return next(err);
    });
  });

  server.get('/.*?', restify.serveStatic({
    directory: './public',
    "default": "index.html"
  }));

  server.listen(config.server.port, config.server.ip, function() {
    return console.log('%s listening at %s', server.name, server.url);
  });

}).call(this);
