// Generated by CoffeeScript 1.7.1
(function() {
  var hasRequiredParameters,
    __slice = [].slice;

  hasRequiredParameters = (function(_this) {
    return function() {
      var param, paramObj, required, _i, _len;
      paramObj = arguments[0], required = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      for (_i = 0, _len = required.length; _i < _len; _i++) {
        param = required[_i];
        if (typeof paramObj[param] === "undefined") {
          return false;
        }
      }
      return true;
    };
  })(this);

  module.exports = {
    hasRequiredParameters: hasRequiredParameters
  };

}).call(this);
