// Generated by CoffeeScript 1.7.1
(function() {
  var DatabaseProvider, Q, pg;

  Q = require('q');

  pg = require('pg');

  DatabaseProvider = (function() {
    function DatabaseProvider(config) {
      this.user = config.user, this.database = config.database, this.password = config.password, this.port = config.port, this.host = config.host, this.ssl = config.ssl;
    }

    DatabaseProvider.prototype.getClient = function() {
      var defer;
      defer = Q.defer();
      pg.connect({
        user: this.user,
        database: this.database,
        password: this.password,
        port: this.port,
        host: this.host,
        ssl: this.ssl
      }, function(err, client, done) {
        if (err) {
          console.log(err);
          return defer.reject(new Error('Could not connect to the database'));
        } else {
          return defer.resolve([client, done]);
        }
      });
      return defer.promise;
    };

    return DatabaseProvider;

  })();

  module.exports = DatabaseProvider;

}).call(this);
